spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/citi-test
    username:
    password: